### ISSUE TITLE
Missing docker ubuntu image for armhf for v.4.4.4

### ISSUE THREAD

**Issue by bjornborg** [chalmers-revere/opendlv.core#72]
/usr/bin/docker: Tag v4.4.4 not found in repository docker.io/seresearch/opendavinci-ubuntu-16.04-armhf-complete.

when running make buildComplete for arm pc. Works well for v.4.4.3. I guess it haven't created the docker image yet.

**Comment by chrberger** [comment]
The next regular release is scheduled for Sat night at 4am.

Do you need it earlier?

**Comment by bjornborg** [comment]
It's alright, I can work in 4.4.3 for now.
