### ISSUE TITLE
Compile warning proxy-velodyne16

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv.core#99]
@HangYin2015 may I ask you to have a look here:

/opt/opendlv.core.sources/code/core/system/proxy-velodyne16/src/ProxyVelodyne16.cpp: In constructor 'opendlv::core::system::proxy::ProxyVelodyne16::ProxyVelodyne16(const int32_t&, char**)':
/opt/opendlv.core.sources/code/core/system/proxy-velodyne16/src/ProxyVelodyne16.cpp:41:1: warning: 'opendlv::core::system::proxy::ProxyVelodyne16::m_intensityPlacement' should be initialized in the member initialization list [-Weffc++]
 ProxyVelodyne16::ProxyVelodyne16(const int32_t &argc, char **argv)

**Comment by HangYin2015** [comment]
@ Thanks for pointing this out. I fixed this issue in a new PR

**Comment by chrberger** [comment]
@HangYin2015 This is fixed now?

**Comment by HangYin2015** [comment]
Dear Christian,
    It is unfortunate that the Internet in my apartment was broken a moment
ago. I will try to fix this issue tomorrow morning.
Best regards,
Hang

Christian Berger <notifications@github.com>于2017年9月25日 周一下午9:50写道：

**Comment by HangYin2015** [comment]
@chrberger Yes. This was fixed long time ago.

**Comment by chrberger** [comment]
Thanks, @HangYin2015
